version: "3.9"

services:
  mongodb:
    image: mongo:7.0-jammy
    container_name: auth-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: auth_db
    volumes:
      - mongodb_data:/data/db
    networks:
      - api-gateway-network

  auth-service:
    build: .
    container_name: auth-service
    # ports:
    #   - "3001:3001"
    environment:
      PORT: 3001
      MONGO_URL: mongodb://admin:password@mongodb:27017/auth_db?authSource=admin
      JWT_SECRET: dev_jwt_secret
      JWT_REFRESH_SECRET: dev_refresh_secret
      EMAIL_USER: vvq0522@gmail.com
      EMAIL_PASS: pyzewbsumidnrqsw
    depends_on:
      - mongodb
    networks:
      - api-gateway-network

volumes:
  mongodb_data:

networks:
  api-gateway-network:
    external: true
